### ISSUE TITLE
System Message > Terms of Service

### ISSUE THREAD

**Issue by klauslovgreen** [Blockstream/green_ios#10]
### Description
Unable to tick the box at the end for "I confirm I have read and understood the above message"
 

I tried scrolling to the end and back - the tick-box cannot be ticked and "Accept" is disabled for the same reason.  

#### Version
3.0.7

### Steps to reproduce

Click the Notifications bell icon at the lower right and click the "System Message" - GreenAddress Terms of Service (which also seems a bit outdated) 

### Expected behaviour

To click the box and accept

### Actual behaviour

Unable to tick the box 

#### Device or machine

iOS 12.2 iPhone XS Max and iPad Pro

**Comment by lvaccaro** [comment]
Thanks, c0f3226 resolves the bug. Next release (tag 3.0.8) will have it

**Comment by domegabri** [comment]
this is fixed. @klauslovgreen reopen otherwise
