### ISSUE TITLE
[Feature request] split satoshis in wallet display

### ISSUE THREAD

**Issue by torkelrogstad** [Blockstream/green_ios#19]
Currently satoshi amounts are displayed without any numerical formatting, like "1234567 sats" in the main wallet overview. This is really hard to visually parse at a glance. Would be great if they could be broken up somehow, for example "1 234 567 sats" or 1,234,567 sats"

**Comment by alessandro-saglimbeni** [comment]
Hey, we are already tracking this and working to fix it. Thanks for your contribution!

**Comment by colinmasters** [comment]
Will be in 3.2.8 release, closing issue accordingly.
