### ISSUE TITLE
Build Fails with "No Such Module PromiseKit"

### ISSUE THREAD

**Issue by nharmon9** [Blockstream/green_ios#20]
### Description

building in XCode fails with `No such module 'PromiseKit'`.
I have tried `pod deintegrate` and `pod install` multiple times.

Also `$ tools/build.sh --iphonesim static` fails to build from the command line, but can find PromiseKit, with:
```
clang: error: no such file or directory: '/Users/bsh/green_ios/gdk-iphone/lib/iphonesim/libgreenaddress_full.a'
Command Ld failed with a nonzero exit code
...

The following build commands failed:
	Ld /Users/bsh/Library/Developer/Xcode/DerivedData/gaios-bjkavaudikevspbfbuioyvfwtkwr/Build/Products/Release-iphonesimulator/gaios.app/gaios normal x86_64

```

Then I add in the directory and copy the files from the /iphone dir which produces:
```
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
...

The following build commands failed:
	Ld /Users/bsh/Library/Developer/Xcode/DerivedData/gaios-bjkavaudikevspbfbuioyvfwtkwr/Build/Products/Release-iphonesimulator/gaios.app/gaios normal x86_64

```
Which makes sense.

#### Version

commit 1ba421c01a1ec204d351978cbde8dd404a2b0c61

#### Device or machine

OSX 10.15.1

**Comment by colinmasters** [comment]
Try downloading the gdk-iphone release build from here: https://github.com/Blockstream/gdk/releases and dropping that into your root folder and see if it builds.

No such module PromiseKit is likely a red herring and something from the gdk setup isn't compiling and therefore preventing PromiseKit from compiling.

**Comment by nharmon9** [comment]
This built thank you. Also I am trying to connect to a local regtest but I always get "you are not connected to the internet." I have the same problem with the android build, what am I doing wrong here???

**Comment by colinmasters** [comment]
Best option is to join the Blockstream Green Telegram group and get support for this kind of issue there: https://t.me/blockstream_green
