### ISSUE TITLE
nlocktime

### ISSUE THREAD

**Issue by morningsprouter** [Blockstream/green_ios#21]
There is no way to get nlocktime.zip, which i guess is one of the most important parts to have if you use the wallet.

Also documentation about nlocktimes.zip is missing, you are prompt to store the seed securely and also you are asked to set up 2fa, but there is no mention that if you loose 2fa you basically lost your wallet. 

The IOS version of green wallet looks as it has been done purely, almost as if management decided to have a IOS app version and the techs kind of slapped it on.

**Comment by domegabri** [comment]
nlocktimes zip files can be received via email once user enabled email 2fa. app was wrongfully hiding options for recovery until user enabled an email.

After 6da24604f94bcebb57295145d707cbda02975fc3 recovery options are always available and will fail with a useful error when used (error suggests that recovery email should be enabled for the request to work). There's also an additional option to enable email just for recovery purposes and not for 2fa.

Additionally Blockstream Green apps will soon switch to use a csv based timelock allowing recovery without additional data other than wallet mnemonic backup, greatly reducing the trust user put in the service.
