### ISSUE TITLE
Unable to complete wallet seed verification if socks proxy cannot connect

### ISSUE THREAD

**Issue by cdelargy** [Blockstream/green_ios#3]
### Description

During initial setup of new wallet, user is unable to complete wallet seed verification if socks proxy cannot connect

#### Version

Latest

### Steps to reproduce

During initial wallet creation, specify a socks proxy and input a hostname such as "bitcoin". Create new wallet. During final verification of seed (select word 4) the app will not continue due to "You are not connected to the internet. Please connect and retry."

### Expected behaviour

App should verify the seed without requiring an internet connection or without requiring the socks proxy to connect

### Actual behaviour

App requires user to return to the initial screen, abandoning seed, to remove socks proxy before validating new seed to continue.

### Screenshots

GUI shows part of attempted new seed during error message, skipping due to abundance of caution ;-)

#### Device or machine

iOS / iphone 8

#### Additional info

tips: 3Lb8MJ7Q7CM9VSxVKUko3UABTjiLommaUw

**Comment by seth586** [comment]
Similar error on android. I have Orbot running and bootstrapped, configured green with localhost:9500

GDK_ERROR_CODE_-2
GA_Connect_with_proxy

**Comment by domegabri** [comment]
The app doesn't need internet connection to verify the seed but to register as a new user to the service. Specifying an invalid proxy doesn't allow you to complete the process. We are thinking of adding a proxy ping to notify this to users before starting the onboarding/login.

**Comment by cdelargy** [comment]
Generally issues remain open until resolved.

**Comment by domegabri** [comment]
Opened https://github.com/Blockstream/gdk/issues/14 in the right place for tracking
