### ISSUE TITLE
Missing release notes?

### ISSUE THREAD

**Issue by RazorII** [Blockstream/green_ios#30]
GitHub release notes up to 3.4.9 but AppStore already has v3.5.0

I'm unable to find the release notes here on GitHub for the version that is available on the AppStore (3.5.0). Could someone point me to the right place.

**Comment by lvaccaro** [comment]
Hi @RazorII, thank to report it.

Push v3.5.0 tag with release notes on https://github.com/Blockstream/green_ios/releases/tag/release_3.5.0
