### ISSUE TITLE
General feedback

### ISSUE THREAD

**Issue by flypaper0** [Blockstream/green_ios#4]
Sorry but code looks like it was made by freelancers. Anyway, the interface looks beautiful. Good luck, guys

P.S.
Please forgive me for not finding a better place to this review

**Comment by bitschmidty** [comment]
@flypaper0 thanks for the feedback!

**Comment by bitschmidty** [comment]
@flypaper0 additionally, if you have any specific feedback/review of the code it would be much appreciated!

**Comment by colinmasters** [comment]
Closing as there are no action steps to take, code improvement is ongoing.
