### ISSUE TITLE
Funds sent to onchain Lightning never completes swap

### ISSUE THREAD

**Issue by bstin** [Blockstream/green_ios#46]
### Description

I don't know if this is a bug, or if there is some misunderstanding about how the workflow goes when funding a LN wallet....but after creating a LN wallet and sending funds funds to its onchain address, the funds "arrive" but it permanently stalls saying "Swapping - Unconfirmed".

This has been stuck like this for 4 days...

#### Version

4.0.16

### Steps to reproduce

1. Create new LN wallet
2. Click "Receive"
3. Click "On chain address"
4. Send funds to that address

### Expected behaviour

Should fund the wallet 

### Actual behaviour

Stalls saying "Unconfirmed - Swapping"

**Comment by bstin** [comment]
![green](https://github.com/Blockstream/green_ios/assets/10012474/f0e27c5b-ac20-4b00-b361-df1236b92b81)

**Comment by bstin** [comment]
![green2](https://github.com/Blockstream/green_ios/assets/10012474/caf0636e-ef2a-49e2-86c5-4ed696d951b6)

**Comment by alessandro-saglimbeni** [comment]
Hi @bstin , is the onchain transaction still unconfirmed? In this case the onchain transaction fees are low and it hasn't gotten confirmations yet.

If it's confirmed, I will need to ask you to open a ticket via our official support channel [1] sharing:
- the transaction ID of such onchain transaction, 
- the Support ID, you can find it within your wallet settings

[1] https://help.blockstream.com/hc/en-us/requests/new?ticket_form_id=8613

**Comment by bstin** [comment]
Yes, the onchain was confirmed within an hour or so of sending. This is part of the confusion of the UI that it says "Swapping Unconfirmed"....I've been waiting a few days for the "swap" to complete, which it never seems to.

I will fill out the form you linked with requested info.

**Comment by alessandro-saglimbeni** [comment]
Thanks for that, we're investigating your issue, we'll continue interacting through the ticket on our support channel until it's solved.

**Comment by bstin** [comment]
Thank you.
