### ISSUE TITLE
Blockstream Support Will Not Respond

### ISSUE THREAD

**Issue by nickdavis333** [Blockstream/green_ios#63]
Has anyone had any luck getting Blockstream Support to respond?  I have tried a request from the website link below and also sent an email to inquiries@blockstream.com as suggested.  I have received absolutely nothing from my email inquiry and only an automatic reply to the ticket I submitted.  It has been 3 weeks since I submitted the ticket and all I get is crickets.  Any help on how to get Blockstream support to answer would be greatly appreciated.  My specific issue is with the Green wallet. 

https://help.blockstream.com/hc/en-us/requests/new?ticket_form_id=8613

Thanks,
Nick

**Comment by nodesupport1** [comment]
@nickdavis333 can you give more details about the issues on your green wallet?

**Comment by jgriffiths** [comment]
Hi @nickdavis333 

Please be aware that the user you have replied to is not a Blockstream account and is not affiliated with Blockstream in any way (I am a Blockstream developer, as you can see from my github profile). You may want to edit your post and remove the address from it. Note you should never post private information including wallet addresses to public forums, and no representative of Blockstream will ever ask you to do so.

I have inquired internally about why your support request appears to have slipped though the cracks and has not been replied to. Please re-raise a support ticket (using the link you posted above) referencing this github issue, and when you get a reply you can close this issue, thanks.

**Comment by nickdavis333** [comment]
Thank you for the help!  I went ahead and submitted another support ticket as you recommended.  Hope to hear back soon.

Thanks you,
Nick

**Comment by alessandro-saglimbeni** [comment]
We're continuing the investigation on the support desk, thanks for raising this Nick

**Comment by nickdavis333** [comment]
Hello Alessandro,

I was initially getting responses from the Blockstream support desk, however they have been completely unresponsive to my last three emails for over 3 weeks now.  So I thought I would try one last attempt on here and see if there is anything you can do to help me get this resolved even if the answer is sorry we don't know what happened.  

Thanks again,
Nick
