### ISSUE TITLE
Blockstream Support Desk Will Not Respond... Again...

### ISSUE THREAD

**Issue by nickdavis333** [Blockstream/green_ios#68]
Hello Alessandro,

I was initially getting responses from the Blockstream support desk, however they have been completely unresponsive to my last three emails for over 3 weeks now.  So I thought I would try one last attempt on here and see if there is anything you can do to help me get this resolved even if the answer is sorry we don't know what happened.  

Thanks again,
Nick

_Originally posted by @nickdavis333 in https://github.com/Blockstream/green_ios/issues/63#issuecomment-2430064795_

**Comment by alessandro-saglimbeni** [comment]
Apologies for the lack of response, please follow up on the ticket
