### ISSUE TITLE
can't create or restore green wallet - false positive of "no internet connection"

### ISSUE THREAD

**Issue by letmeloveU** [Blockstream/green_ios#9]
### Description

I created a new wallet on iOS green wallet but when I verify my mnemonic seed, the 8th entry a pop-up says "You are not connected to the internet. Please connect and retry". Even when I try to restore I get the same error. But i'm constantly connected to the internet so that error is incorrect.

### Steps to reproduce
Write down provided mnemonic seed.
App asks to verify certain sequence of the mnemonic seed,
On the 8 seed entry I get an error saying I have no internet connection (which is false)

### Expected behaviour

A new wallet should be created or restored.
### Actual behaviour

Got the following pop-up:
"You are not connected to the internet. Please connect and retry"
### Screenshots

![image](https://user-images.githubusercontent.com/45417715/54877343-c822ef80-4e25-11e9-9dad-d9117914b760.png)
#### Device or machine

iOS XR

**Comment by domegabri** [comment]
Does this happen on the fourth word asked? Have you turned proxy/tor settings on?

**Comment by bitschmidty** [comment]
@letmeloveU have you been able to work through this issue? If not, let us know if you have proxy/tor enabled
